[colors.primary]
background = "0x160126"
foreground = "0xCCC9C2"

[colors.normal]
black = "0x212733"
red = "0xF28779"
green = "0xBAE67E"
yellow = "0xFFCC66"
blue = "0x73D0FF"
magenta = "0xD4BFFF"
cyan = "0x5CCFE6"
white = "0xffffff"

[colors.bright]
black = "0x666666"
red = "0xff3334"
green = "0x9ec400"
yellow = "0xe7c547"
blue = "0x7aa6da"
magenta = "0xb77ee0"
cyan = "0x54ced6"
white = "0xffffff"

[colors.dim]
black = "0x333333"
red = "0xf2777a"
green = "0x99cc99"
yellow = "0xffcc66"
blue = "0x6699cc"
magenta = "0xcc99cc"
cyan = "0x66cccc"
white = "0xdddddd"

[colors.cursor]
text = "0x000000"
cursor = "0xffffff"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window]
opacity = 0.9
#decorations = "transparent"
#dynamic_title = true
#startup_mode = "Windowed"
#startup_mode = "Fullscreen"

[window.dimensions]
columns = 130
lines = 36

[window.padding]
x = 20
y = 60

[[keyboard.bindings]]
chars = "\u0013"
key = "S"
mods = "Command"

[[keyboard.bindings]]
key = "F"
mods = "Command"
action = "ToggleSimpleFullscreen"

[[keyboard.bindings]]
key = "R"
mods = "Command"
chars = "\u0012"  # This is ^R, same as Ctrl+R

#[[keyboard.bindings]]
#key = "K"
#mods = "Command"
#action = "ToggleSimpleFullscreen"
# Disable any default Cmd+T binding

# [[keyboard.bindings]]
# key = "T"
# mods = "Command"
# action = "CreateNewTab"

# Optional: keep ⌘N for a real new window
[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "O"
mods = "Command"
chars = "\u001b[1;9o"

[general]
live_config_reload = true

[selection]
save_to_clipboard = true
