#!/bin/bash

yt-dlp --print filename   --output "%(cast|join:, |or:uploader)s - [%(channel,uploader)s] %(title)s (%(extractor)s) [%(resolution)s].%(ext)s"   https://www.xvideos.com/video.okfdffmbf5d/couple_swap_with_our_neighbor-_tabatha_lust_-_yasmina_khan
