#!/usr/bin/env python3
"""Generate config/zsh/completions/_yt-dlp from the installed yt-dlp.

Homebrew's keg ships a zsh completion, but install-yt-dlp.sh unlinks that keg
(so the brew binary cannot shadow the uv build), and `brew unlink` removes the
completion from site-functions along with the binary. The uv build ships none.
So the completion is checked in here and regenerated from the live option
parser, which keeps it in sync with whatever yt-dlp is actually installed.

Mirrors yt-dlp's own devscripts/zsh-completion.py, which is not part of the
wheel. Run with the interpreter that has yt_dlp importable — install-yt-dlp.sh
uses the uv tool venv's python.

Usage: gen-yt-dlp-completion.py OUTPUT_PATH
"""

import sys

import yt_dlp
from yt_dlp.options import create_parser

TEMPLATE = """#compdef yt-dlp
# Generated by setup/install/gen-yt-dlp-completion.py from yt-dlp {version}.
# Do not edit by hand; re-run setup/install/install-yt-dlp.sh.

__yt_dlp() {{
    local curcontext="$curcontext" fileopts diropts cur prev
    typeset -A opt_args
    fileopts="{fileopts}"
    diropts="{diropts}"
    cur=$words[CURRENT]
    case $cur in
        :)
            _arguments '*: :(::ytfavorites ::ytrecommended ::ytsubscriptions ::ytwatchlater ::ythistory)'
        ;;
        *)
            prev=$words[CURRENT-1]
            if [[ ${{prev}} =~ ${{fileopts}} ]]; then
                _path_files
            elif [[ ${{prev}} =~ ${{diropts}} ]]; then
                _path_files -/
            elif [[ ${{prev}} == "--remux-video" ]]; then
                _arguments '*: :(mp4 mkv)'
            elif [[ ${{prev}} == "--recode-video" ]]; then
                _arguments '*: :(mp4 flv ogg webm mkv)'
            else
                _arguments '*: :({flags})'
            fi
        ;;
    esac
}}

__yt_dlp
"""


def main(out_path):
    parser = create_parser()
    opts = [opt for group in parser.option_groups for opt in group.option_list]
    opts_file = [opt.get_opt_string() for opt in opts if opt.metavar == 'FILE']
    opts_dir = [opt.get_opt_string() for opt in opts if opt.metavar == 'DIR']
    flags = [opt.get_opt_string() for opt in opts]

    with open(out_path, 'w') as f:
        f.write(TEMPLATE.format(
            version=yt_dlp.version.__version__,
            fileopts='|'.join(opts_file),
            diropts='|'.join(opts_dir),
            flags=' '.join(flags),
        ))


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
