#!/bin/bash
# Generated by bin/build-installer.py. Edit installer/install-propainter.template.sh.
set -euo pipefail
UPSTREAM_COMMIT=e870e79321c31b733e2031af5aa2fb1fe3ac7eec
UV_VERSION=0.11.14
DEST="$HOME/src/scrubber"
SMOKE=1
usage() {
  cat <<'HELP'
Install ProPainter for Apple Silicon macOS (M1/M2/M3/M4 and newer).
Usage: bash install-propainter.sh [--dir PATH] [--skip-smoke-test]
Default destination: ~/src/scrubber
Installs an isolated Python 3.12 environment, pinned dependencies, launchers,
and verified model weights. Runs a six-frame repair by default.
No Homebrew, administrator access, or preinstalled Python required.
HELP
}
fail() { printf 'Error: %s\n' "$*" >&2; exit 1; }
while [ "$#" -gt 0 ]; do
  case "$1" in
    --dir) [ "$#" -ge 2 ] && [ -n "$2" ] || fail '--dir needs a path'; DEST="$2"; shift 2 ;;
    --skip-smoke-test) SMOKE=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) fail "Unknown argument: $1 (use --help)" ;;
  esac
done
[ "$(uname -s)" = Darwin ] || fail 'This installer is for macOS.'
[ "$(uname -m)" = arm64 ] || fail 'Run from a native Apple Silicon terminal, not Rosetta.'
mkdir -p "$DEST"
DEST=$(cd "$DEST" && pwd -P)
WORK=$(mktemp -d "${TMPDIR:-/tmp}/scrubber-install.XXXXXX")
trap 'rm -rf "$WORK"' EXIT
trap 'printf "Installation interrupted; rerun the same command to resume.\n" >&2; exit 130' INT TERM
mkdir -p "$DEST/.cache" "$DEST/.tools"
# Concurrent installation into one destination can corrupt its environment.
LOCK="$DEST/.cache/install.lock"
mkdir "$LOCK" 2>/dev/null || fail "Another install may be running. If none is running, remove $LOCK and retry."
trap 'rm -rf "$WORK"; rmdir "$LOCK"' EXIT

# Embedded files are generated from the tracked, tested launcher and lockfile.
mkdir "$WORK/payload"
base64 -D <<'SCRUBBER_PAYLOAD' | tar -xz -C "$WORK/payload"
H4sIAAAAAAAC/+1XW2/bNhTus34Fpw2otVqyJV9yQQWsydK1WNoEafcwBIHAyJTFWhJVknKsFv3v
O4e0EzfpZQ9r16I6LyYPz52HR58le91wyUpWaeWXNBUqKES6uPdf0hBoOh6bX6Dbv+Ekuj6z/DAa
gzgZ3vsK1ChNJbi/92MSnc14quM4CsbB0KFVy0Ucj4NwEoQOXcZxuBuEcJAyqXnGQW4YTYOdIIqc
NKdSMe1XQpa04G+YjONRgHppwdNFHO/CBjRFpUUj6xZsGR9pmxYoOwzCCIQZr0StcLsbRE7GC4b9
hzGAgJOBthaiUMiYor1MqZql60D2kNHoRjK0PoRdHobG9BTXmb9iGk/MTus6FRvJPbNfoWwEKTp5
M5/zap7RlPl5c4lCowi0+KyimFcEy5LOGZYnCkY7wXiz97OsrNkcLaGbV7x6RSNUAbfOgl9xJYol
Jhya4hT0TesXgs5sDSZOSeWiqRXNGCoNgxFwdF0IXfBLYyaEupQ1MHMTFfiomL4ScrHC4ynYrJoS
6xuBg5EjalalS79udS6qOJ5gWYK9kVPTdEExRxCcglzNi0JcgcnI2KwLqjO4yhmXptjgNgyduq3h
lo3SCMQix5r1Z1SzRvMCncIlBLVQGmy0LS2BNzVpSBgtTGllCjYGXcxRs0oJub7voaNSvuDaN6U0
dzG1TNsu2HwO9FhTr3tgd2wuWfGVOd7BdVuuhbG5oEkz7KHr/ggnwCtLe+nRnqOFTHOMCL2bzZIr
joWCY6yDfj0rMf8dbD/d1pC7z1YYNkjZymCMjSzgfkYbSy2tMzQxRhPf0/uXTZXUUtSUV5rJoG6/
gI/Pzv+d0a35H452uvn/Vch13bOmIjCAtGS0JKdSnNpeIFdc56SGsaOIZDAd+JIRLYjOGeHVUizg
ZRCYFiyFZ9QGYAgmYi2kJkI5mRSl0YVHQtbsU9huRKDt6nazUa1yHCmEJrER6iUJvuEk8QLJzPTs
eQHMIcAoDpVzBWKgEsByeR7uXzjoJxG1xgcKZ29dn7t94vr+ks+YMMvSMkqqFmZlub5odN1o9x18
ZyThfQImITfCYKAyCSOuh+68fYcA8YxwQqsZCqlzTnwSXqDwtncriWSFLjBULXsmK2B5AVvVYKNR
TPa2svOMHivAhxu7aBUjWTsLVF1w3YODPgm98+EnvC5Y2ydLWjQMHN9R/UBwoEAeGJ8PbgI1Bj4e
KgRZwV0BVuhRDOXtnXISqCYN8GFphV3Uuz6LXY9grek6x01xcRmYMTvrnd9Y6pugTGsMiAsxNIVW
rnfhOdcNG5PN8U3rug7A2DSH5uxt5DwHWwarFvAKUtK9oTV+LWAlsKnA5vn2ERrnVcagAVP2/rR0
vT75FYO/cExLB2aeYhGvO3R40cd2TypasthNkhKUk8T1vo3PxCWvBjcZfRkfONR3JpOPzf/hOAxv
zf/hNIq6+f816OefBtgCb1SOQIv4rHFeHJ79dXBwdJacnZy8jN1f3g73H+3n+/k714GRYCb53y9P
zg6fJEfPHx0cHyXPTl8kjx8dHx88OvwzDjdCz06PD0+eP376x+9Pz8DKe1YHQUrTnA1ukO61bWv5
ycmzo48pGdSG8iwld0SWrFqajCxQde9I3AE8KPKb6/yg94+lUqVYMF8DVv9f3n84nka33/9kHHbv
/9t7/59/bv7tB+eShw/vw8B4cvL8/mdhocrxT+U2LtyGhTegDwAAogglGpmyPplB6/KKIhhCXHHe
cy/LlQ/fbqYQmGQSPr0KP9VbB8kGC+IvYgoLRKAZ5kxvoYoN6MC1fSi8QmgC+y23W7pBuUDgYfGq
il/KBiJkK650IhZma4GYgZz4vxdDhv/Ems16vQ9gGYs+wKWNQVy+AsSdSFYKwGnIslXwAg7S6Nnz
zvenFzeg0BY1SEXdRj3jsb9Jc2AjCBCbeI69pQ8P1vdxAtyzBdd3x6st12CrVIN1/YnF3/9KxV4K
2QDBT+ug3BWfwb+VUTSEdc74PNck3ItgU+HmUsikYNUcRKbAU82liX6bJ1mWANwDtt3STCdYUTJG
BbpkiU3jR/1QdNRRRx111FFHHXXUUUcdddRRRx119F3SP3GDZm4AKAAA
SCRUBBER_PAYLOAD
for file in requirements-macos.lock run_propainter.py bin/propainter bin/smoke-test; do
  if [ -e "$DEST/$file" ]; then
    cmp -s "$WORK/payload/$file" "$DEST/$file" || fail "Existing $DEST/$file differs; use another --dir to preserve your changes."
  fi
done

printf '\nInstalling into %s\n' "$DEST"
# Keep uv and its Python installations local; no shell-profile changes.
UV="$DEST/.tools/uv"
if [ ! -x "$UV" ]; then
  curl --fail --location --retry 3 "https://astral.sh/uv/$UV_VERSION/install.sh" -o "$WORK/uv-install.sh"
  UV_UNMANAGED_INSTALL="$DEST/.tools" sh "$WORK/uv-install.sh"
fi
export UV_CACHE_DIR="$DEST/.cache/uv"
export UV_PYTHON_INSTALL_DIR="$DEST/.tools/python"
export UV_PYTHON_BIN_DIR="$DEST/.tools/bin"

if [ -d "$DEST/ProPainter/.git" ]; then
  actual=$(git -C "$DEST/ProPainter" rev-parse HEAD)
  [ "$actual" = "$UPSTREAM_COMMIT" ] || fail 'Existing ProPainter checkout is at another revision; use a new --dir.'
  [ -z "$(git -C "$DEST/ProPainter" status --porcelain --untracked-files=no)" ] || fail 'Existing ProPainter has source edits; use a new --dir.'
elif [ -e "$DEST/ProPainter" ]; then
  [ -f "$DEST/ProPainter/.scrubber-upstream-commit" ] || fail 'Unrecognised ProPainter directory; use a new --dir.'
  [ "$(cat "$DEST/ProPainter/.scrubber-upstream-commit")" = "$UPSTREAM_COMMIT" ] || fail 'Installed source revision differs; use a new --dir.'
else
  printf '\nDownloading pinned ProPainter source...\n'
  curl --fail --location --retry 3 "https://codeload.github.com/sczhou/ProPainter/tar.gz/$UPSTREAM_COMMIT" -o "$WORK/source.tar.gz"
  mkdir "$WORK/source"
  tar -xzf "$WORK/source.tar.gz" --strip-components=1 -C "$WORK/source"
  printf '%s\n' "$UPSTREAM_COMMIT" > "$WORK/source/.scrubber-upstream-commit"
  mv "$WORK/source" "$DEST/ProPainter"
fi
if [ -e "$DEST/.venv" ]; then
  [ -x "$DEST/.venv/bin/python" ] || fail 'Existing .venv is incomplete; choose a new --dir or repair it first.'
  "$DEST/.venv/bin/python" -c 'import sys, platform; assert sys.version_info[:2] == (3,12) and platform.machine() == "arm64", "Python 3.12 arm64 required"'
else
  "$UV" venv --python 3.12 --managed-python "$DEST/.venv"
fi
# Files are copied only after all existing versions have been checked.
mkdir -p "$DEST/bin"
for file in requirements-macos.lock run_propainter.py bin/propainter bin/smoke-test; do
  cp "$WORK/payload/$file" "$DEST/$file"
done
chmod +x "$DEST/bin/propainter" "$DEST/bin/smoke-test"
"$UV" pip sync --python "$DEST/.venv/bin/python" "$DEST/requirements-macos.lock"
"$UV" pip check --python "$DEST/.venv/bin/python"

mkdir -p "$DEST/ProPainter/weights"
while read -r name expected; do
  target="$DEST/ProPainter/weights/$name"
  if [ -f "$target" ]; then
    actual=$(shasum -a 256 "$target" | awk '{print $1}')
    [ "$actual" = "$expected" ] || fail "Checksum mismatch for existing $target; move it aside and retry."
    printf 'Verified existing %s\n' "$name"
    continue
  fi
  curl --fail --location --retry 3 "https://github.com/sczhou/ProPainter/releases/download/v0.1.0/$name" -o "$WORK/$name"
  actual=$(shasum -a 256 "$WORK/$name" | awk '{print $1}')
  [ "$actual" = "$expected" ] || fail "Checksum mismatch for downloaded $name"
  mv "$WORK/$name" "$target"
done <<'WEIGHTS'
ProPainter.pth 12c070c4b48f374c91d8a2a17851140b85c159621080989f9e191bbc18bd6591
raft-things.pth fcfa4125d6418f4de95d84aec20a3c5f4e205101715a79f193243c186ac9a7e1
recurrent_flow_completion.pth 22939a1a7900da878dbe1ccd011d646b1bfb30b8290039d8ff0e0c2fefbfd283
WEIGHTS
"$DEST/.venv/bin/python" - <<'PY'
import torch
print('PyTorch:', torch.__version__)
print('Apple GPU available:', torch.backends.mps.is_available())
if not torch.backends.mps.is_available():
    raise SystemExit('Apple GPU unavailable. Check macOS/PyTorch support before running ProPainter.')
PY
"$DEST/bin/propainter" --help > "$WORK/help.txt"
if [ "$SMOKE" = 1 ]; then
  printf '\nRunning sample repair (first launch may build caches)...\n'
  "$DEST/bin/smoke-test"
  "$DEST/.venv/bin/python" - "$DEST/results/smoke/frames/inpaint_out.mp4" <<'PY'
import sys
import torchvision
frames, _, info = torchvision.io.read_video(sys.argv[1], pts_unit='sec')
assert tuple(frames.shape) == (6, 192, 320, 3), frames.shape
assert info['video_fps'] == 24, info
print('Verified sample export: six 320x192 frames at 24 fps.')
PY
fi
printf '\nInstallation complete.\nLauncher: %s/bin/propainter\nSample test: %s/bin/smoke-test\n' "$DEST" "$DEST"
printf 'Upstream exports silent video and resizes the whole frame; crop/composite and audio preservation are not included.\n'
printf 'License: ProPainter/LICENSE (S-Lab, non-commercial use).\n'
