[package]
name = "menu-tidy"
version = "0.1.0"
edition = "2024"

[dependencies]
block2 = "0.6.2"
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", features = [
    "NSApplication",
    "NSAttributedString",
    "NSButton",
    "NSColor",
    "NSFont",
    "NSFontDescriptor",
    "NSGraphics",
    "NSImage",
    "block2",
    "NSControl",
    "NSEvent",
    "NSMenu",
    "NSMenuItem",
    "NSResponder",
    "NSScreen",
    "NSStatusBar",
    "NSStatusBarButton",
    "NSWindow",
    "NSText",
    "NSView",
] }
objc2-core-foundation = { version = "0.3.2", features = ["CFArray", "CFDictionary", "CFNumber", "CFString"] }
objc2-core-graphics = { version = "0.3.2", features = ["CGWindow"] }
objc2-foundation = { version = "0.3.2", features = [
    "NSArray",
    "NSAttributedString",
    "NSDictionary",
    "NSUserDefaults",
    "NSDate",
    "NSEnumerator",
    "NSGeometry",
    "NSObject",
    "NSRunLoop",
    "NSString",
    "NSThread",
    "NSTimer",
] }

[profile.release]
opt-level = "s"
lto = true
strip = true
