theme = "dark_plus"

[editor]
true-color = true
shell = ["zsh", "-c"]
bufferline = "always"

[keys.normal]
Cmd-a = "select_all"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-p = ["move_line_up", "scroll_up"]
C-s = [":w!"]
y = ":clipboard-yank"
Y = [":clipboard-yank", "collapse_selection"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
H = ["goto_line_start"]
D = ["insert_mode", "kill_to_line_end", "normal_mode"]
d = ["delete_selection"]
S-backspace = "delete_selection"
p = ":clipboard-paste"
0 = ["goto_line_start"]
L = ["goto_line_end"]
V = ["extend_line", "select_mode"]
"{" = ["goto_prev_paragraph", "collapse_selection", "normal_mode"]
"}" = ["goto_next_paragraph", "move_line_down", "collapse_selection", "normal_mode"]
Q = ":wq!"
backspace = "goto_last_accessed_file"
# Move current line down (Shift+J)
G = "goto_last_line"
J = [
  "extend_line",       # select the current line
  "delete_selection",  # cut it
  "paste_after",       # drop it one line down
  "collapse_selection" # reset the selection so you can do it again
]
# Move current line up (Shift+K)
K = [
  "extend_line",         # select the current line
  "delete_selection",    # cut it
  "move_line_up",        # go up to the line above
  "move_line_up",        # (extra so you land above the right spot)
  "paste_after",         # paste here
  "collapse_selection"   # reset the selection for the next repeat
]
"C-=" = "expand_selection"
"C-minus" = "shrink_selection"
"Cmd-c" = ["yank_main_selection_to_clipboard"]
"Cmd-v" = [":clipboard-paste-after"]

[keys.insert]
C-s = [":write", "normal_mode"]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]

[keys.select]
D = ["yank_main_selection_to_clipboard", "delete_selection"]
S-backspace = "delete_selection"
Cmd-backspace = "delete_selection"
Cmd-a = "select_all"
'{' = "goto_prev_paragraph"
'}' = "goto_next_paragraph"
H = "goto_line_start"
L = "goto_line_end"
# yank selection into system clipboard
y = [":clipboard-yank"]
# yank main (joined) selection into system clipboard
Y = [":clipboard-yank", "collapse_selection"]
J = ["delete_selection", "paste_after"]
K = ["delete_selection", "move_visual_line_up", "paste_before"]
# make “p” replace the current selection with the system clipboard
p = [":clipboard-paste-replace", "collapse_selection"]
# full-line extend down
j = "extend_line_below"
# full-line extend up
k = "extend_line_above"
R = ["replace_selections_with_clipboard"]
"C-+" = "expand_selection"
"C-minus" = "shrink_selection"
esc = ["collapse_selection", "normal_mode"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
