theme = "tokyonight"

[editor.whitespace]
# render = "all"

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
C-s = [":w!"]
esc = ["collapse_selection", "keep_primary_selection"]
D = ["insert_mode", "kill_to_line_end", "normal_mode"]
H = ["goto_line_start"]
0 = ["goto_line_start"]
L = ["goto_line_end"]
V = ["goto_line_start", "select_mode", "goto_line_end"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
Q = ":wq!"
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme tokyonight_storm"]
backspace = "goto_last_accessed_file"
p = [":clipboard-paste-after"]
P = [":clipboard-paste-before"]

[keys.insert]
C-s = [":write", "normal_mode"]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]

[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
H = ["goto_line_start"]
L = ["goto_line_end"]
y = [":clipboard-yank"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
