[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 2, unit = "\t" }
roots = ["Cargo.toml"]

[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "solidity"
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "xml"
file-types = [ "xml", "svg", "xsd", "xslt", "xsl" ]
auto-format = true
formatter = { command = "xmllint", args = ["--format", "-"] }
language-servers = [ "xml" ]

[language-server.xml]
command = "lemminx-osx-aarch_64"
