[options]

    colorscheme = "darkblue"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "nil"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    relativenumber = false
    bootstrap_after = 'customconfig#after'
    filemanager = "nerdtree"
    enable_filetree_status = true
    enable_vimfiler_welcome = false

[[layers]]
name = "lsp"
enabled_clients = ["rustup", "typescript-language-server"]
filetypes = ["rust", "javascript"]
    
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "fzf"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#typescript"

[[custom_plugins]]
name = 'lilydjwg/colorizer'
merged = 0


#[[custom_plugins]]
#name = 'simrat39/symbols-outline'
#merged = 0

