[helpers]

[default]
depends = []

[default.files]

[default.variables]

[nvim-container]
files = { nvim-container = "~/.config/nvim" }

[nvim-root]
files = { "nvim/root.lua" = "/root/.config/nvim/init.lua", "nvim/shared.lua" = "/root/.config/nvim/lua/shared.lua" }

[bash]
files = { "bash/rc.bash" = "~/.bashrc", "bash/fzm.bash" = "~/.bash/fzm.bash" }

[sway]
[sway.files]
"sway" = "~/.config/sway"
"fuzzel/fuzzel.ini" = "~/.config/fuzzel/fuzzel.ini"
"yambar" = "~/.config/yambar"
"waybar" = "~/.config/waybar"

[nvim]
files = { "nvim" = "~/.config/nvim" }

[foot]
files = { "foot/foot.ini" = "~/.config/foot/foot.ini" }

[xdg]
files = { "xdg-applications" = "~/.local/share/applications" }

[lf]
[lf.files]
"lf/lfrc.conf" = { target = "~/.config/lf/lfrc", type = "symbolic" }
"lf/pv.sh" = "~/.config/lf/pv.sh"
