[helpers]

[default]
depends = []

[default.files]

[default.variables]
"colorscheme" = "zellner"
"zk_path" = "/mnt/data/notes/zk"

[alacritty]
files = { "alacritty" = "~/.config/alacritty" }

[nvim-container]
files = { nvim-container = "~/.config/nvim" }

[nvim-root]
files = { "nvim/root.lua" = "/root/.config/nvim/init.lua", "nvim/shared.lua" = "/root/.config/nvim/lua/shared.lua" }

[bash]
files = { "bash/rc.bash" = "~/.bashrc", "bash/fzm.bash" = "~/.bash/fzm.bash" }

[sway]
[sway.files]
"sway.conf" = "~/.config/sway/config"
"yambar.yml" = "~/.config/yambar/config.yml"
"waybar" = "~/.config/waybar"

[nvim]
files = { "neovim.lua" = "~/.config/nvim/init.lua", "snippets" = "~/.config/nvim/snippets" }
# variables = { "colorscheme" = "darkblue" }

[foot]
files = { "foot/foot.ini" = "~/.config/foot/foot.ini" }

[xdg]
files = { "xdg-applications" = "~/.local/share/applications" }

[helix]
files = { "helix" = "~/.config/helix" }

[lf]
[lf.files]
"lf/lfrc.conf" = { target = "~/.config/lf/lfrc", type = "symbolic" }
"lf/pv.sh" = "~/.config/lf/pv.sh"
