# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio     = [ 1, 4, 3 ]
scrolloff = 5

[preview]
max_width  = 1200
max_height = 900

[opener]
edit = [
	{ run = "${EDITOR:-vi} %s", desc = "$EDITOR", for = "unix", block = true },
	{ run = "hx %s", desc = "helix", for = "unix", block = true },
	{ run = "code %s", desc = "code", for = "windows", orphan = true },
	{ run = "code -w %s", desc = "code (block)", for = "windows", block = true },
]
play = [
	{ run = "mpv --force-window %s", desc = "mpv", for = "unix", orphan = true },
	{ run = "vlc %s .", desc = "vlc", for = "unix", orphan = true },
	{ run = "tag %s", desc = "tag", for = "unix", orphan = true },
	{ run = "mediainfo %s1; echo 'Press enter to exit'; read _", desc = "mediainfo", for = "unix", block = true },
]
play_dir = [
	{ run = "mpv --force-window %s", desc = "mpv", for = "unix", orphan = true },
	{ run = "vlc %s .", desc = "vlc", for = "unix", orphan = true },
]
open = [
	{ run = "xdg-open %s1", desc = "Open", for = "linux" },
	{ run = "open %s", desc = "Open", for = "macos" },
	{ run = 'start "" %s1', desc = "Open", for = "windows", orphan = true },
]
reveal = [
	{ run = "xdg-open %d1", desc = "Reveal", for = "linux" },
	{ run = "open -R %s1", desc = "Reveal", for = "macos" },
	{ run = "explorer /select,%s1", desc = "Reveal", for = "windows", orphan = true },
	{ run = "clear; exiftool %s1; echo 'Press enter to exit'; read _", desc = "Show EXIF", for = "unix", block = true },
]
extract = [
	{ run = "ya pub extract --list %s", desc = "Extract here" },
]

[open]
prepend_rules = [
	{ url = "*/", use = [ "edit", "open", "reveal", "play_dir" ] },
]

[plugin]
append_previewers = [
	{ url = "*", run = "file-extra-metadata" },
]
append_spotters = [
	{ url = "*", run = "file-extra-metadata" },
]

[[plugin.prepend_fetchers]]
group = "mactag"
url   = "*"
run   = "mactag"

[[plugin.prepend_fetchers]]
group = "mactag"
url   = "*/"
run   = "mactag"

[[plugin.prepend_fetchers]]
group = "ffmpeg_stats"
url   = "*"
run   = "ffmpeg-stats"
