[helpers]

[default]
depends = []

[delta.files]
"delta/gitconfig" = "~/.gitconfig"

[default.files]

[default.variables]
"colorscheme" = "zellner"
"zk_path" = "/mnt/data/notes/zk"

[bin.files]
"bin" = { target = "~/.bin/", type = "symbolic" }

[joshuto.files]
"joshuto" = "~/.config/joshuto"

[yazi.files]
"apps/yazi" = "~/.config/yazi"

[chafa.files]
"scripts/chafa-select" = "~/.bin/chafa-select"

[zellij.files]
"zellij" = { target = "~/.config/zellij", type = "symbolic" }

[mpv.files]
"mpv" = "~/.config/mpv"

[alacritty]
files = { "alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml" }

[kitty]
files = { "kitty" = "~/.config/kitty" }

[nu]
files = { "nu" = "~/.config/nushell" }

[skhd]
files = { "skhd/skhd.conf" = "~/.config/skhd/skhdrc" }

[bash]
files = { "bash/rc.bash" = "~/.bashrc", "bash/fzm.bash" = "~/.bash/fzm.bash" }

[sway]
[sway.files]
"sway.conf" = "~/.config/sway/config"
"yambar.yml" = "~/.config/yambar/config.yml"
"waybar" = "~/.config/waybar"

[nvim]
files = { "neovim" = "~/.config/nvim" }
#files = { "neovim.lua" = "~/.config/nvim/init.lua", "snippets" = "~/.config/nvim/snippets" }
# variables = { "colorscheme" = "darkblue" }

[foot]
files = { "foot/foot.ini" = "~/.config/foot/foot.ini" }

[xdg]
files = { "xdg-applications" = "~/.local/share/applications" }

[helix]
files = { "helix" = "~/.config/helix" }

[starship]
files = { "starship/starship.toml" = "~/.config/starship.toml" }

[lf]
[lf.files]
"lf/lfrc.conf" = { target = "~/.config/lf/lfrc", type = "symbolic" }
"lf/pv.sh" = "~/.config/lf/pv.sh"
"lf/icons" = "~/.config/lf/icons"
"lf/colors" = "~/.config/lf/colors"

[zsh]
[zsh.files]
"zsh/zshrc.zsh" = "~/.zshrc"
"zsh/emoji.json" = "~/.zsh/emoji.json"
"zsh/scripts/" = "~/.zsh/scripts"
"zsh/completions/" = "~/.zsh/completions"
"zsh/autoload/" = "~/.zsh/autoload"
"zsh/bin/" = "~/.zsh/bin"

[dotter]
files = { "dotter/global.toml" = "~/.config/dotter/global.toml" }

[gitui]
files = { "gitui/vim.ron" = "~/.config/gitui/key_bindings.ron" }
